name: "Test submodule"
description: "Testing sub"
inputs:
  env_filter_sub:
    description: 'blah'
    required: true
runs:
  using: "composite"
  steps:
    - name: Branch and Event for now
      shell: bash
      run: |
        echo "Running on branch: ${{ github.ref }}"
        echo "Running up to environment: ${{ inputs.env_filter_sub }}"
        echo "This is definitely new"
        echo "Im in this repo: ${{ github.event.repository.name }}"
    - name: Checkout templates repo
      uses: actions/checkout@v2
      with:
        repository: efairgrieveorg/recipes
    - name: ls
      shell: bash
      run: |
        ls -lha    
    - name: Pickup AWS Creds and Terraform Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
        role-session-name: GitHubActions-${{ github.event.repository.name }}
        role-duration-seconds: 3600
    # - name: terraform init
    #   shell: bash
    #   run: |
    #     terraform init -backend-config="bucket=efairgrieve-terraform-states" -backend-config="key=${{ env.TF_VAR_env }}-${{ github.event.repository.name }}-state" 
    # - name: terraform plan
    #   shell: bash
    #   run: |
    #     terraform plan -out=plan.output
    # - name: terraform apply
    #   shell: bash
    #   run: terraform apply -auto-approve -input=false plan.output